### ISSUE TITLE
Boring slide show

### ISSUE THREAD

**Issue by jvargas** [alejovargas/github-slideshow#4]
This should be more spiffy. Can you add some content and some graphics?

**Comment by alejovargas** [comment]
I don't care

**Comment by jvargas** [comment]
Common. Really this is your image. Try something new.

**Comment by alejovargas** [comment]
OK. I'll take care of it @jvargas

**Comment by jvargas** [comment]
Neat!

**Comment by alejovargas** [comment]
Address in the #5
